# Generated by Django 5.2.3 on 2025-07-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgidesk_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiscalprofile",
            name="invoice_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
