# Generated by Django 5.2.3 on 2025-07-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgidesk_app", "0002_fiscalprofile_invoice_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fiscalprofile",
            old_name="business_type",
            new_name="business_name",
        ),
        migrations.RemoveField(
            model_name="fiscalprofile",
            name="birthdate",
        ),
        migrations.RemoveField(
            model_name="fiscalprofile",
            name="income",
        ),
        migrations.AddField(
            model_name="fiscalprofile",
            name="currency",
            field=models.CharField(
                choices=[("EUR", "EUR"), ("GBP", "GBP"), ("USD", "USD")],
                default="EUR",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="fiscalprofile",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
        migrations.AddField(
            model_name="fiscalprofile",
            name="iban",
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AddField(
            model_name="fiscalprofile",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="user_logos/"),
        ),
        migrations.AddField(
            model_name="fiscalprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="fiscalprofile",
            name="vat_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="fiscalprofile",
            name="vat_registered",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="fiscalprofile",
            name="pps_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
